// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Hospital.Models;

public partial class BenhVienContext : DbContext
{
    public BenhVienContext(DbContextOptions<BenhVienContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }

    public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }

    public virtual DbSet<BenhNhan> BenhNhan { get; set; }

    public virtual DbSet<NhanVien> NhanVien { get; set; }

    public virtual DbSet<TaiKhoan> TaiKhoan { get; set; }

    public virtual DbSet<Thuoc> Thuoc { get; set; }

    public virtual DbSet<ToaThuoc> ToaThuoc { get; set; }

    public virtual DbSet<ToaThuocChiTiet> ToaThuocChiTiet { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AspNetRoles>(entity =>
        {
            entity.HasIndex(e => e.NormalizedName, "RoleNameIndex")
                .IsUnique()
                .HasFilter("([NormalizedName] IS NOT NULL)");

            entity.Property(e => e.Name).HasMaxLength(256);
            entity.Property(e => e.NormalizedName).HasMaxLength(256);
        });

        modelBuilder.Entity<AspNetUsers>(entity =>
        {
            entity.HasIndex(e => e.NormalizedEmail, "EmailIndex");

            entity.HasIndex(e => e.NormalizedUserName, "UserNameIndex")
                .IsUnique()
                .HasFilter("([NormalizedUserName] IS NOT NULL)");

            entity.Property(e => e.Email).HasMaxLength(256);
            entity.Property(e => e.NormalizedEmail).HasMaxLength(256);
            entity.Property(e => e.NormalizedUserName).HasMaxLength(256);
            entity.Property(e => e.UserName).HasMaxLength(256);

            entity.HasMany(d => d.Role).WithMany(p => p.User)
                .UsingEntity<Dictionary<string, object>>(
                    "AspNetUserRoles",
                    r => r.HasOne<AspNetRoles>().WithMany().HasForeignKey("RoleId"),
                    l => l.HasOne<AspNetUsers>().WithMany().HasForeignKey("UserId"),
                    j =>
                    {
                        j.HasKey("UserId", "RoleId");
                        j.HasIndex(new[] { "RoleId" }, "IX_AspNetUserRoles_RoleId");
                    });
        });

        modelBuilder.Entity<BenhNhan>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__BenhNhan__3213E83F734143EF");

            entity.HasIndex(e => e.Email, "UQ__BenhNhan__A9D105347E1F625A").IsUnique();

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.Cmnd)
                .HasMaxLength(12)
                .IsUnicode(false)
                .IsFixedLength()
                .HasColumnName("CMND");
            entity.Property(e => e.DiaChi).HasMaxLength(100);
            entity.Property(e => e.Email).HasMaxLength(50);
            entity.Property(e => e.Ho).HasMaxLength(40);
            entity.Property(e => e.NgaySinh).HasColumnType("date");
            entity.Property(e => e.Ten).HasMaxLength(10);
        });

        modelBuilder.Entity<NhanVien>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__NhanVien__3213E83F0A2DD5C3");

            entity.HasIndex(e => e.Email, "UQ__NhanVien__A9D10534DD514672").IsUnique();

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.DiaChi).HasMaxLength(100);
            entity.Property(e => e.DienThoai)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.Email).HasMaxLength(50);
            entity.Property(e => e.Ho).HasMaxLength(40);
            entity.Property(e => e.Khoa).HasMaxLength(40);
            entity.Property(e => e.Luong).HasColumnType("money");
            entity.Property(e => e.NgaySinh).HasColumnType("date");
            entity.Property(e => e.Ten).HasMaxLength(10);

            entity.HasOne(d => d.IdNavigation).WithOne(p => p.NhanVien)
                .HasForeignKey<NhanVien>(d => d.Id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__NhanVien__id__15502E78");
        });

        modelBuilder.Entity<TaiKhoan>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TaiKhoan__3213E83F091E01F9");

            entity.HasIndex(e => e.Email, "UQ__TaiKhoan__A9D1053440736DD7").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Email).HasMaxLength(50);
            entity.Property(e => e.Password).HasMaxLength(10);
            entity.Property(e => e.VaiTro).HasMaxLength(10);
        });

        modelBuilder.Entity<Thuoc>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Thuoc__3213E83FC5E6374C");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CongDung).HasMaxLength(50);
            entity.Property(e => e.DonGia).HasColumnType("money");
            entity.Property(e => e.DonVi).HasMaxLength(20);
            entity.Property(e => e.Loai).HasMaxLength(20);
            entity.Property(e => e.Ten).HasMaxLength(20);
        });

        modelBuilder.Entity<ToaThuoc>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ToaThuoc__3213E83F06232C21");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.ChanDoan).HasMaxLength(200);
            entity.Property(e => e.IdBacSi).HasColumnName("id_BacSi");
            entity.Property(e => e.IdBenhNhan).HasColumnName("id_BenhNhan");
            entity.Property(e => e.Ngay).HasColumnType("date");
            entity.Property(e => e.TinhTrang).HasMaxLength(15);

            entity.HasOne(d => d.IdBacSiNavigation).WithMany(p => p.ToaThuoc)
                .HasForeignKey(d => d.IdBacSi)
                .HasConstraintName("FK__ToaThuoc__id_Bac__1DE57479");

            entity.HasOne(d => d.IdBenhNhanNavigation).WithMany(p => p.ToaThuoc)
                .HasForeignKey(d => d.IdBenhNhan)
                .HasConstraintName("FK__ToaThuoc__id_Ben__1ED998B2");
        });

        modelBuilder.Entity<ToaThuocChiTiet>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ToaThuoc__3213E83FD5C366CD");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CachDung).HasMaxLength(10);
            entity.Property(e => e.Chieu).HasMaxLength(10);
            entity.Property(e => e.IdThuoc).HasColumnName("id_Thuoc");
            entity.Property(e => e.IdToaThuoc).HasColumnName("id_ToaThuoc");
            entity.Property(e => e.Sang).HasMaxLength(10);
            entity.Property(e => e.Trua).HasMaxLength(10);

            entity.HasOne(d => d.IdThuocNavigation).WithMany(p => p.ToaThuocChiTiet)
                .HasForeignKey(d => d.IdThuoc)
                .HasConstraintName("FK__ToaThuocC__id_Th__22AA2996");

            entity.HasOne(d => d.IdToaThuocNavigation).WithMany(p => p.ToaThuocChiTiet)
                .HasForeignKey(d => d.IdToaThuoc)
                .HasConstraintName("FK__ToaThuocC__id_To__239E4DCF");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}