// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hospital.Models;

public partial class NhanVien
{
    public int Id { get; set; }

    public string Ho { get; set; }

    public string Ten { get; set; }

    public DateTime? NgaySinh { get; set; }

    public bool? GioiTinh { get; set; }

    public string Khoa { get; set; }

    public string Email { get; set; }

    public string DienThoai { get; set; }

    public string DiaChi { get; set; }

    public decimal? Luong { get; set; }

    public string ChucVu { get; set; }
    public virtual TaiKhoan IdNavigation { get; set; }

    public virtual ICollection<ToaThuoc> ToaThuoc { get; set; } = new List<ToaThuoc>();
}