// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hospital.Models;

public partial class TaiKhoan
{
    public int Id { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string VaiTro { get; set; }

    public virtual NhanVien NhanVien { get; set; }
}