// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hospital.Models;

public partial class Thuoc
{
    public int Id { get; set; }

    public string Ten { get; set; }

    public string CongDung { get; set; }

    public string Loai { get; set; }

    public string DonVi { get; set; }

    public decimal? DonGia { get; set; }

    public virtual ICollection<ToaThuocChiTiet> ToaThuocChiTiet { get; set; } = new List<ToaThuocChiTiet>();
}