// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Hospital.Models;

public partial class ToaThuocChiTiet
{
    public int Id { get; set; }

    public int? IdThuoc { get; set; }

    public int? IdToaThuoc { get; set; }

    public byte? SoLuong { get; set; }

    public string Sang { get; set; }

    public string Trua { get; set; }

    public string Chieu { get; set; }

    public string CachDung { get; set; }

    public virtual Thuoc IdThuocNavigation { get; set; }

    public virtual ToaThuoc IdToaThuocNavigation { get; set; }
}